spring:
  application:
    name: bookstracker

  cassandra:
    keyspace-name: main
    username: <username>
    password: <password>
    schema-action: create_if_not_exists
    request:
      timeout: 30s
    connection:
      connect-timeout: 30s
      init-query-timeout: 30s


datastax.astra:
  secure-connect-bundle: src/main/resources/secure-connect.zip

astra.db:
  id: <db-id>
  region: <db-region>
  keyspace: main
  application.token: <application-token>

