spring:
  application:
    name: bookstracker

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <client-id>
            client-secret: <client-secret>

  cassandra:
    keyspace-name: main
    username: <username>
    password: <password>
    schema-action: create_if_not_exists
    request:
      timeout: 30s
    connection:
      connect-timeout: 30s
      init-query-timeout: 30s
    username: cassandra
    password: cassandra
    local-datacenter: datacenter1


datastax.astra:
  secure-connect-bundle: src/main/resources/secure-connect.zip

  # local data source
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

